# Generated by Django 3.1.1 on 2021-09-21 04:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0006_auto_20210921_0306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweeetLike',
            new_name='TweetLike',
        ),
    ]
